import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ErrorMapping {
  getUserError(code: string): string {
    const errorMapping: Record<string, string> = {
      NETWORK_ERROR: 'Network error, try again later.',
      SESSION_EXPIRED: 'Session expired, log in again.',
      USER_NOT_FOUND: 'User not found.',
      FILL_ALL_FIELDS: 'Please fill all the required fields.',
      INVALID_CREDENTIALS: 'Invalid credentials, try again.',
      INSERT_FAILED: 'Insert in database failed, try again.',
      AUTH_FAILED: 'Authentication failed, try again.',
      'auth/invalid-credentials': 'Invalid credentials',
      'auth/user-not-found': 'User not found',
      'auth/wrong-password': 'Wrong password',
      'auth/email-already-in-use': 'Email already in use',
      'auth/invalid-email': 'Invalid email',
      'auth/weak-password': 'Weak password',
      '42501': 'Insufficient privileges to perform this action',
      user_already_exists: 'Email already in use',
      invalid_credentials: 'Invalid email or password',
      TICKET_NOT_FOUND: 'Ticket not found.',
      UNKNOWN_ERROR: 'Something went wrong, try again.',
      CHAT_FETCH_FAILED: 'Error fetching chats, try again.',
      CHAT_SEND_FAILED: 'Error sending message, try again.',
      CHAT_UPDATE_FAILED: 'Error updating chat, try again.',
      TICKET_UPDATE_FAILED: 'Error updating ticket, try again.',
      TICKET_DELETE_FAILED: 'Error deleting ticket, try again.',
      TICKET_CREATE_FAILED: 'Error creating ticket, try again.',
      KANBAN_UPDATE_FAILED: 'Error updating board, try again.',
      DATE_CONVERSION_FAILED: 'Error converting date',
      TIMESTAMP_CONVERSION_FAILED: 'Error converting timestamp',
      LOCATION_PARSING_FAILED: 'Error parsing location data',
      USER_LOAD_FAILED: 'Error loading user profile, try again.',
      USER_UPDATE_FAILED: 'Error updating user, try again.',
      USER_DELETE_FAILED: 'Error deleting user, try again.',
      USER_CREATE_FAILED: 'Error creating user, try again.',
      TEAM_FETCH_FAILED: 'Error fetching teams, try again.',
      TEAM_UPDATE_FAILED: 'Error updating team, try again.',
      TEAM_DELETE_FAILED: 'Error deleting team, try again.',
      TEAM_CREATE_FAILED: 'Error creating team, try again.',
      DASHBOARD_LOAD_FAILED: 'Error loading dashboard, try again.',
      CALENDAR_LOAD_FAILED: 'Error loading calendar, try again.',
      CHART_LOAD_FAILED: 'Error loading charts, try again.',
      MAP_LOAD_FAILED: 'Error loading map, try again.',
      DATA_FETCH_FAILED: 'Error fetching data, try again.',
      DATA_UPDATE_FAILED: 'Error updating data, try again.',
      DATA_DELETE_FAILED: 'Error deleting data, try again.',
      DATA_SAVE_FAILED: 'Error saving data, try again.',
      VALIDATION_FAILED: 'Validation failed, check your input.',
      PERMISSION_DENIED: 'You do not have permission to perform this action.',
      RESOURCE_NOT_FOUND: 'Resource not found.',
      CONFLICT: 'This action conflicts with existing data.',
      RATE_LIMIT: 'Too many requests, please try again later.',
      SERVICE_UNAVAILABLE: 'Service temporarily unavailable, try again later.',
      TIMEOUT: 'Request timed out, try again.',
      // Supabase PostgreSQL/Database Error Codes
      '42P01': 'Database table not found.',
      '42703': 'Database column not found.',
      '23505': 'This record already exists.',
      '23503': 'Cannot delete - record is referenced by other data.',
      '22000': 'Invalid input data format.',
      '22001': 'Text data is too long.',
      '22003': 'Numeric value out of range.',
      '22012': 'Division by zero.',
      '23514': 'Data violates database constraints.',
      '42883': 'Database function not found.',
      '42882': 'Function argument type mismatch.',
      '08000': 'Database connection error.',
      '08003': 'Connection does not exist.',
      '08006': 'Connection failure.',
      '57P03': 'Database is shutting down.',
      '42602': 'Invalid name format.',
      '3F000': 'Database not found.',
      '28000': 'Invalid authorization specification.',
      '28P01': 'Authentication failed.',
      // Supabase Auth Error Codes
      'auth/operation_not_allowed': 'Operation not allowed.',
      'auth/invalid-api-key': 'Invalid API key.',
      'auth/session-not-found': 'Session not found, please log in again.',
      'auth/otp-disabled': 'One-time password is disabled.',
      'auth/otp-expired': 'One-time password has expired.',
      'auth/otp-used': 'One-time password already used.',
      'auth/mfa-factor-already-exists': 'This factor already exists.',
      'auth/mfa-factor-not-found': 'MFA factor not found.',
      'auth/invalid-phone': 'Invalid phone number.',
      // Supabase Common Error Codes
      PGRST116: 'Requested range invalid.',
      PGRST301: 'JSON structure invalid.',
      PGRST204: 'No content.',
      INTERNAL_ERROR: 'Internal server error, please try again later.',
  
      BAD_REQUEST: 'Bad request, check your input.',
      UNAUTHORIZED: 'Unauthorized access.',
      FORBIDDEN: 'Access forbidden.',
      NOT_FOUND: 'Resource not found.',
      CONFLICT_ERROR: 'Data conflict, please refresh and try again.',
      UNPROCESSABLE_ENTITY: 'Invalid data provided.',
      TOO_MANY_REQUESTS: 'Too many requests, please wait before trying again.',
      GATEWAY_TIMEOUT: 'Request timeout, please try again.',
      UNKNOWN: 'Something went wrong, try again.',
    };

    return errorMapping[code] ?? errorMapping['UNKNOWN'];
  }
}
